Update add-package-to-json.yml

diff --git a/.github/workflows/add-package-to-json.yml b/.github/workflows/add-package-to-json.yml
--- a/.github/workflows/add-package-to-json.yml
+++ b/.github/workflows/add-package-to-json.yml
@@ -30,6 +30,8 @@ jobs:
         run: |
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
           git config --global user.name "${{ github.actor }}"
+          echo "Failed to create package version"
+          exit 1
 
       # Create a new branch for the changes
       - name: Create a new branch and commit changes
