Update salesforce-cicd.yml

diff --git a/.github/workflows/salesforce-cicd.yml b/.github/workflows/salesforce-cicd.yml
--- a/.github/workflows/salesforce-cicd.yml
+++ b/.github/workflows/salesforce-cicd.yml
@@ -42,7 +42,12 @@ jobs:
         if: steps.step3.outcome == 'success'
         id: step4
         run: |
-          CREATE_OUTPUT=$(sfdx force:package:version:create --package ${{ secrets.PACKAGE_NAME }} --installation-key Sscdre1p --wait 10 -n ${{ github.sha }} --json)
+          echo "Creating package version for package: ${{ secrets.PACKAGE_NAME }} with version: ${{ github.sha }}"
+          CREATE_OUTPUT=$(sfdx force:package:version:create --package ${{ secrets.PACKAGE_NAME }} --installation-key Sscdre1p --wait 10 -n ${{ github.sha }} --json)|| {
+            echo "Failed to create package version"
+            echo "Create Output: $CREATE_OUTPUT"
+            exit 1
+          }
           echo "Create Output: $CREATE_OUTPUT"
           PACKAGE_VERSION_ID=$(echo $CREATE_OUTPUT | jq -r '.result.SubscriberPackageVersionId')
           echo "PACKAGE_VERSION_ID=$PACKAGE_VERSION_ID" >> $GITHUB_ENV
